import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Auth Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {






  return (
    <div className="min-h-screen my-2 mx-auto ">
      <div className="flex justify-center items-center">
        <div className="  w-full mx-auto">{children}</div>
      </div>
    </div>
  );
}
